trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  bbuildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'